@uri = http://localhost:5555/admin/api
@json = Content-Type: application/json
@ajson = Accept: application/json
@auth = Authorization: Bearer xxx

###
POST {{uri}}/login
{{json}}
{{ajson}}

{
  "username": "admin",
  "password": "123456"
}