@uri = http://localhost:5555/api
@json = Content-Type: application/json
@ajson = Accept: application/json
@auth = Authorization: Bearer xxx

###
POST {{uri}}/login
{{json}}
{{ajson}}

{
  "mobile": "17621443042",
  "password": "123456"
}

###
POST {{uri}}/index